<h3>
Name: Jonathan Lawrence<br/>
Date: 7-12-2019<br/>
Assignment: Midterm Project - Landslides<br/>
</h3>

<b>Question for Analysis:</b> In the past few years, what continent has experienced the biggest landslides the most frequently?<br/>

<b>Dataset:</b> Retrieved from NASA.gov (Dated 2007-2018)<br/>
<b>Link:</b> https://data.nasa.gov/Earth-Science/Global-Landslide-Catalog/h9d8-neg4

<b>
<ul>
<li>Replace headers (Data Wrangling with Python pg. 154 –163)</li>
<li>Format Data to a Readable Format (Data Wrangling with Python pg. 164 –168)</li>
<li>Identify outliers and bad data (Data Wrangling with Python pg. 169 –174)</li>
<li>Find Duplicates (Data Wrangling with Python pg. 175 –178)</li>
<li>Conduct Fuzzy Matching (if you don’t have an obvious example to do this with in your data, create categories and use Fuzzy Matching to lump data together) (Data Wrangling with Python pg. 179 –188)</li>
    </ul></b>

In [1]:
import pandas as pd

# Import data (na_filter set to False so that 'NA' is not seen as 'NaN')
df = pd.read_csv(r'landslide_data.csv', na_filter = False)

# show first 5 rows
df.head(5)

,the_geom,OBJECTID,id,date_,time_,country,nearest_pl,hazard_typ,landslide_,trigger,...,population,countrycod,continentc,key_,version,user_id,tstamp,changeset_,latitude,longitude
0,POINT (-73.40200000000006 41.55850000000008),1,3177,03/07/2011 08:00:00 AM +0000,12/30/1899 08:00:00 AM +0000,United States,Grove Street from Anderson Avenue to Hine Hill...,landslide,Mudslide,Downpour,...,6523,,NA,US,1,1,Tue Apr 01 2014 00:00:00 GMT+0000 (UTC),1,41.5585,-73.4020
1,POINT (113.91710000000012 0.1115000000000351),2,490,04/01/2008 07:00:00 AM +0000,,Indonesia,"Borneo, Muara",landslide,Landslide,Rain,...,0,,AS,ID,1,1,Tue Apr 01 2014 00:00:00 GMT+0000 (UTC),1,0.1115,113.9171
2,POINT (-127.69800000000009 52.35450000000008),3,6760,01/30/2015 08:00:00 AM +0000,12/30/1899 08:00:00 AM +0000,,"Ocean Falls, B.C.",landslide,Mudslide,Rain,...,8987,,NA,CA,2,7,Tue Feb 17 2015 15:42:41 GMT+0000 (UTC),3910846556,52.3545,-127.6980
3,POINT (-127.50620000000009 50.70530000000013),4,2494,09/24/2010 07:00:00 AM +0000,,Canada,"road to Holberg, 3 km from hwy 19, Vancouver I...",landslide,Complex,Downpour,...,33430,,NA,CA,1,1,Tue Apr 01 2014 00:00:00 GMT+0000 (UTC),1,50.7053,-127.5062
4,POINT (-132.41490000000013 53.331900000000125),5,6415,08/31/2014 07:00:00 AM +0000,12/30/1899 08:00:00 AM +0000,,Rennell Sound Road,landslide,Mudslide,Downpour,...,14708,,NA,CA,1,7,Thu Dec 04 2014 15:14:07 GMT+0000 (UTC),1280292118,53.3319,-132.4149

<b>Replace headers (Data Wrangling with Python pg. 154 –163)</b><br/>
The headers have trailing '_', a mix of uppercase and lowercase, and are not capitalized.

In [2]:
# Fast method for storing headers in a variable
header = df.columns.values.tolist()
#print("Header:\n" + str(header))

data_rows = [d for d in df]
#print("\nDataframe:\n" + str(df))

# Create list to store corrected headers
corrected_headers = []

# Modify headers for (trailing '_') & (lowercase) & (capitalize)
corrected_headers = [i.replace("_", "").lower().capitalize() if i[-1] == "_" else i.lower().capitalize() for i in header]
#print(corrected_headers)

# Assign new column headers
df.columns = corrected_headers

df.head(5)

,The_geom,Objectid,Id,Date,Time,Country,Nearest_pl,Hazard_typ,Landslide,Trigger,...,Population,Countrycod,Continentc,Key,Version,User_id,Tstamp,Changeset,Latitude,Longitude
0,POINT (-73.40200000000006 41.55850000000008),1,3177,03/07/2011 08:00:00 AM +0000,12/30/1899 08:00:00 AM +0000,United States,Grove Street from Anderson Avenue to Hine Hill...,landslide,Mudslide,Downpour,...,6523,,NA,US,1,1,Tue Apr 01 2014 00:00:00 GMT+0000 (UTC),1,41.5585,-73.4020
1,POINT (113.91710000000012 0.1115000000000351),2,490,04/01/2008 07:00:00 AM +0000,,Indonesia,"Borneo, Muara",landslide,Landslide,Rain,...,0,,AS,ID,1,1,Tue Apr 01 2014 00:00:00 GMT+0000 (UTC),1,0.1115,113.9171
2,POINT (-127.69800000000009 52.35450000000008),3,6760,01/30/2015 08:00:00 AM +0000,12/30/1899 08:00:00 AM +0000,,"Ocean Falls, B.C.",landslide,Mudslide,Rain,...,8987,,NA,CA,2,7,Tue Feb 17 2015 15:42:41 GMT+0000 (UTC),3910846556,52.3545,-127.6980
3,POINT (-127.50620000000009 50.70530000000013),4,2494,09/24/2010 07:00:00 AM +0000,,Canada,"road to Holberg, 3 km from hwy 19, Vancouver I...",landslide,Complex,Downpour,...,33430,,NA,CA,1,1,Tue Apr 01 2014 00:00:00 GMT+0000 (UTC),1,50.7053,-127.5062
4,POINT (-132.41490000000013 53.331900000000125),5,6415,08/31/2014 07:00:00 AM +0000,12/30/1899 08:00:00 AM +0000,,Rennell Sound Road,landslide,Mudslide,Downpour,...,14708,,NA,CA,1,7,Thu Dec 04 2014 15:14:07 GMT+0000 (UTC),1280292118,53.3319,-132.4149

<b>Format Data to a Readable Format (Data Wrangling with Python pg. 164 –168)</b><br/>The variable for size is called 'Landslide1'. It would be best to change that to something more readable like 'Landslide_Size'. Print the data in a format for easy viewing of columns and data.

In [3]:
# Change 'Landslide1' to Landslide_Size
df.rename(columns={'Landslide1':'Landslide_Size'}, inplace=True)

# This can be iterated for each row
print(df.iloc[0])

The_geom               POINT (-73.40200000000006 41.55850000000008)
Objectid                                                          1
Id                                                             3177
Date                                   03/07/2011 08:00:00 AM +0000
Time                                   12/30/1899 08:00:00 AM +0000
Country                                               United States
Nearest_pl        Grove Street from Anderson Avenue to Hine Hill...
Hazard_typ                                                landslide
Landslide                                                  Mudslide
Trigger                                                    Downpour
Storm_name
Fatalities                                                        0
Injuries                                                          0
Source_nam
Source_lin        http://www.newstimes.com/local/article/New-Mil...
Location_a                                        Known_within_1_km
Landslide_Size                                               Medium
Photos_lin
Cat_src                                                         glc
Cat_id                                                         3177
Countrynam                                            United States
Near                                                    New Milford
Distance                                                    2.12825
Adminname1                                              Connecticut
Adminname2                                        Litchfield County
Population                                                     6523
Countrycod
Continentc                                                       NA
Key                                                              US
Version                                                           1
User_id                                                           1
Tstamp                      Tue Apr 01 2014 00:00:00 GMT+0000 (UTC)
Changeset                                                         1
Latitude                                                    41.5585
Longitude                                                   -73.402
Name: 0, dtype: object

<b>Identify outliers and bad data (Data Wrangling with Python pg. 169 –174)</b><br/>The data for size contains values like 'nan' (blank) and 'unknown'.

In [4]:
##### Landslide_Size #####
# Show all unique values in Landslide_Size
print("Landslide_Size (before): " + str(df['Landslide_Size'].unique()))

# Omit data with value 'unknown' or blank ('')
badValues = df['Landslide_Size'].isin(['unknown', ''])
df = df[~badValues]

print("Landslide_Size (after): " + str(df['Landslide_Size'].unique()))

##### cContinentc ##### There are no blank values here.
print("\nContinentc: " + str(df['Continentc'].unique()))

Landslide_Size (before): ['Medium' 'Small' 'Large' 'Very_large' 'unknown' 'large' 'medium' 'small'
 'Extra Large' '']
Landslide_Size (after): ['Medium' 'Small' 'Large' 'Very_large' 'large' 'medium' 'small'
 'Extra Large']

Continentc: ['NA' 'AS' 'SA' 'OC' 'EU' 'AF']

<b>Find Duplicates(Data Wrangling with Python pg. 175 –178)</b><br/>The 'Id' column should be unique for every landslide. There should be no duplicates.

In [5]:
# Find all rows containing similar values for the 'Id' column
df[df.duplicated(['Id'], keep=False)]

# No duplicates detected.

Empty DataFrame
Columns: [The_geom, Objectid, Id, Date, Time, Country, Nearest_pl, Hazard_typ, Landslide, Trigger, Storm_name, Fatalities, Injuries, Source_nam, Source_lin, Location_a, Landslide_Size, Photos_lin, Cat_src, Cat_id, Countrynam, Near, Distance, Adminname1, Adminname2, Population, Countrycod, Continentc, Key, Version, User_id, Tstamp, Changeset, Latitude, Longitude]
Index: []

[0 rows x 35 columns]

<b>Conduct Fuzzy Matching (if you don’t have an obvious example to do this with in your data, create categories and use Fuzzy Matching to lump data together) (Data Wrangling with Python pg. 179 –188)</b>

In this step, I want to merge the capitalized and non-capitalized versions of each of my values (i.e. 'small' and 'Small') so that they appear as the same value. There were also many entries listed as 'Large' or 'Very_large' and just one entry listed as 'Extra large'. Since we don't know the distinction between them, I want to simplify the scale down to three options:
<ul>
<li>Small</li>
<li>Medium</li>
<li>Large</li>
</ul>

Since the values are clearly distinct, fuzzy-matching is not really required here, but I am going to use it to show how certain I am of which values belong together before I merge them.

In [6]:
# Open .txt file containing all valid sizes
with open("Landslide_Sizes.txt", "r") as f:
    sizes = f.read().split("\n")

# use fuszzywuzzy
from fuzzywuzzy import process

def get_matches(query, choices, limit=2):
    results = process.extract(query, choices, limit = limit)
    return results

print("Check for 'small': " + str(get_matches("small", sizes)))
print(">>>100% match with 'Small'")

print("\nCheck for 'medium': " + str(get_matches("medium", sizes)))
print(">>>100% match with 'Medium'")

print("\nCheck for 'large': " + str(get_matches("large", sizes)))
print(">>>100% match with 'Large'")

print("\nCheck for 'Very_large': " + str(get_matches("Very_large", sizes)))
print(">>>90% match with 'Large'")

print("\nCheck for 'Extra large': " + str(get_matches("Extra large", sizes)))
print(">>>90% match with 'Large'")

# Rename values
df['Landslide_Size'].replace(['small'],'Small', inplace=True)
df['Landslide_Size'].replace(['medium'],'Medium', inplace=True)
df['Landslide_Size'].replace(['large'],'Large', inplace=True)
df['Landslide_Size'].replace(['Very_large'],'Large', inplace=True)
df['Landslide_Size'].replace(['Extra Large'],'Large', inplace=True)

print("\n\nFINAL VALUE CATEGORIES: " + str(df['Landslide_Size'].unique()))

Check for 'small': [('Small', 100), ('Large', 20)]
>>>100% match with 'Small'

Check for 'medium': [('Medium', 100), ('Small', 18)]
>>>100% match with 'Medium'

Check for 'large': [('Large', 100), ('Small', 20)]
>>>100% match with 'Large'

Check for 'Very_large': [('Large', 90), ('Small', 18)]
>>>90% match with 'Large'

Check for 'Extra large': [('Large', 90), ('Small', 36)]
>>>90% match with 'Large'


FINAL VALUE CATEGORIES: ['Medium' 'Small' 'Large']

C:\Users\Jonathan\Anaconda3\lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

<b>Recall our question for analysis:</b> In the past few years, what continent has experienced the biggest landslides the most frequently?

In [7]:
# View list of all continents in the data
# print("Continents: " + str(df['Continentc'].unique()))

# Create variables to store data from individual continents
df_NA = df[(df['Continentc']=="NA") & (df['Landslide_Size']=="Large")]
df_AS = df[(df['Continentc']=="AS") & (df['Landslide_Size']=="Large")]
df_SA = df[(df['Continentc']=="SA") & (df['Landslide_Size']=="Large")]
df_OC = df[(df['Continentc']=="OC") & (df['Landslide_Size']=="Large")]
df_EU = df[(df['Continentc']=="EU") & (df['Landslide_Size']=="Large")]
df_AF = df[(df['Continentc']=="AF") & (df['Landslide_Size']=="Large")]

# Create list of continents
continentList = df['Continentc'].unique()

# Create list to store quantities
quantityList = [len(df_NA.index), len(df_AS.index), len(df_SA.index), len(df_OC.index), len(df_EU.index), len(df_AF.index)]

max_value = max(quantityList)
max_index = quantityList.index(max_value)

print("Continent with the most frequent 'biggest' landslides: " + str(continentList[max_index]))
print("Number of 'biggest' landslides in that continent: " + str(max_value))

Continent with the most frequent 'biggest' landslides: AS
Number of 'biggest' landslides in that continent: 362